---
- name: Enable archive
  ios_config:
    parents:
      - archive
    lines:
      - "path flash:"

# - name: register the ssh key for scp
#   copy:
#     contents: "{{ ansible_password }}"
#     dest: "{{ playbook_dir }}/ssh_key"
#   delegate_to: localhost
#   run_once: yes

- debug: var=hostvars.inventory_hostname

- name: Push device configs
  command: "scp -i ansible_ssh_private_key_file /archived_configs/{{ inventory_hostname }}/config/running.cfg ec2-user@{{ inventory_hostname }}:/running.config"
