---
- name: Enable archive
  ios_config:
    parents:
      - archive
    lines:
      - "path flash:"

# - name: register the ssh key for scp
#   copy:
#     contents: "{{ ansible_password }}"
#     dest: "{{ playbook_dir }}/ssh_key"
#   delegate_to: localhost
#   run_once: yes


- name: Push device configs
  command: "scp -i /home/ec2-user/.ssh/aws-private.pem -o StrictHostKeyChecking=no  /archived_configs/{{ inventory_hostname }}/config/running.cfg ec2-user@{{ inventory_hostname }}:/running.config"
  become: yes

- name: Replace config
  ios_command:
    commands:
      - show clock
      - "dir flash:"
      - configure replace flash:running.config force
