---
- name: Enable archive
  ios_config:
    parents:
      - archive
    lines:
      - "path flash:"
- name: Push device configs
  command: "scp /archived_configs/{{ inventory_hostname }}/config/running.cfg {{ inventory_hostname }}:/running.config"
  become: yes
  become_user: ec2-user
