---
- name: Enable archive
  ios_config:
    parents:
      - archive
    lines:
      - "path flash:"

# - name: register the ssh key for scp
#   copy:
#     contents: "{{ ansible_password }}"
#     dest: "{{ playbook_dir }}/ssh_key"
#   delegate_to: localhost
#   run_once: yes


- debug:
    msg: "{{ secret_key }}"

- shell: "cat {{ secret_key }}"
  register: key

- debug: var=key

- name: Push device configs
  command: "scp -i {{ secret_key }} /archived_configs/{{ inventory_hostname }}/config/running.cfg ec2-user@{{ inventory_hostname }}:/running.config"
