---
- name: Ensure that the caretaker user is present
  ios_user:
    name: caretaker
    privilege: 15
    nopassword: true
    sshkey: ../files/caretaker_telco.pub
    state: present

- name: Push device configs
  command: "scp -i {{ secret_key }} -o StrictHostKeyChecking=no  /archived_configs/{{ inventory_hostname }}/config/running.cfg caretaker@{{ inventory_hostname }}:/running.config"

- name: Enable archive
  ios_config:
    parents:
      - archive
    lines:
      - "path flash:"

- name: Replace config
  ios_command:
    commands:
      - config replace flash:running.config force
