---
- name: Sync to devices
  hosts: all
  gather_facts: no
  vars:
    sot_repo: "git@github.com:redhattelco/caretaker-sot.git"

  tasks:
    - name: GATHER THE ARCHIVED CONFIGS
      git:
        repo: "{{ sot_repo }}"
        clone: yes
        dest: "/archived_configs"
        key_file: "{{ secret_key }}" #Passed in from Tower git creds
        accept_hostkey: true
      delegate_to: localhost
      run_once: yes

    - name: Include the appropriate network devices
      include_tasks: "{{ ansible_network_os }}.yml"
      ignore_errors: yes
      when: ansible_network_os is defined
